apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: NodePort
  selector:
    app: mi-app-log   # ðŸ”¥ conecta con los Pods
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
