apiVersion: v1
kind: Service
metadata:
  name: my-log-service
spec:
  type: NodePort
  selector:
    app: my-logs   # ðŸ”¥ conecta con los Pods
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
